export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'
export const CHANGE_IS_ADD_GOAL = 'CHANGE_IS_ADD_GOAL'
export const CHANGE_ENTERED_GOAL = 'CHANGE_ENTERED_GOAL'
export const SET_ALL_GOALS = 'SET_ALL_GOALS'
